apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crane-agent
rules:
  - apiGroups:
      - ""
    resources:
      - pods/status
      - pods
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - nodeqosensurancepolicies.ensurance.crane.io
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - podqosensurancepolicies.ensurance.crane.io
    verbs:
      - get
      - list
      - watch
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crane-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crane-agent
subjects:
  - kind: ServiceAccount
    name: crane-agent
    namespace: crane-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crane-agent
  namespace: crane-system
