apiVersion: ensurance.crane.io/v1alpha1
kind: NodeQOSEnsurancePolicy
metadata:
  name: "sched"
  labels:
    app: "system"
spec:
  nodeQualityProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 10
    nodeLocalGet:
      localCacheTTLSeconds: 60
  objectiveEnsurances:
    - name: "container_sched_run_queue_time"
      reachedThreshold: 1
      restoredThreshold: 10
      actionName: "throttle"
      dryRun: false
      metricRule:
        metric:
          name: "container_sched_run_queue_time"
        target:
          type: "Value"
          value: 500