apiVersion: ensurance.crane.io/v1alpha1
kind: NodeQOSEnsurancePolicy
metadata:
  name: "waterline1"
  labels:
    app: "system"
spec:
  nodeQualityProbe: 
    initialDelaySeconds: 10
    timeoutSeconds: 10
    nodeLocalGet:
      localCacheTTLSeconds: 60
  objectiveEnsurances:
  - name: "cpu_usage"
    avoidanceThreshold: 2
    restoredThreshold: 2
    actionName: "disablescheduled"
    metricRule:
      name: "cpu_total_usage"
      value: 4000
